"""create app roles and users

Revision ID: 97b1ddf51c6c
Revises:
Create Date: 2026-05-27 22:09:12.448413

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97b1ddf51c6c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_roles_name"), "app_roles", ["name"], unique=True)
    op.create_table(
        "app_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("keycloak_user_id", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "team",
            sa.Enum(
                "customer_support",
                "fraud",
                "case_management",
                name="staff_team",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["app_roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_app_users_email"),
        sa.UniqueConstraint("username", name="uq_app_users_username"),
    )
    op.create_index(op.f("ix_app_users_email"), "app_users", ["email"], unique=True)
    op.create_index(
        op.f("ix_app_users_keycloak_user_id"),
        "app_users",
        ["keycloak_user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_app_users_role_id"), "app_users", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_app_users_username"), "app_users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_users_username"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_role_id"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_keycloak_user_id"), table_name="app_users")
    op.drop_index(op.f("ix_app_users_email"), table_name="app_users")
    op.drop_table("app_users")
    op.drop_index(op.f("ix_app_roles_name"), table_name="app_roles")
    op.drop_table("app_roles")
    # ### end Alembic commands ###
