from .escalation_summary import (
    CUSTOMER_NAME_EXTRACTION_PROMPT,
    ESCALATION_SUMMARY_PROMPT,
)
from .fallback_response import DATA_FALLBACK_RESPONSE_PROMPT

__all__ = [
    "CUSTOMER_NAME_EXTRACTION_PROMPT",
    "DATA_FALLBACK_RESPONSE_PROMPT",
    "ESCALATION_SUMMARY_PROMPT",
]
