from .fallback_response import DATA_FALLBACK_RESPONSE_PROMPT
from .investigation import (
    EVIDENCE_GAPS_PROMPT,
    RECOMMENDATION_PROMPT,
    RISK_INDICATORS_PROMPT,
)

__all__ = [
    "DATA_FALLBACK_RESPONSE_PROMPT",
    "EVIDENCE_GAPS_PROMPT",
    "RECOMMENDATION_PROMPT",
    "RISK_INDICATORS_PROMPT",
]
